esphome:
  name: esp01
  platform: ESP8266
  board: nodemcuv2

captive_portal:

# Enable logging
logger:

ota:

sensor:
  - platform: adc
    pin: A0
    id: pot_position
    update_interval: 100ms
    filters:
      - calibrate_linear:
          - 0.8 -> 0.0
          - 0.2 -> 1.0
      - lambda: return clamp(x, 0, 1);
  - platform: template
    name: "My Stepper Position"
    id: position
    lambda: return id(my_stepper).current_position;
    
api:
  services:
    - service: control_blind
      variables:
        target: int
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return target;'
        - sensor.template.publish:
            id: position
            state: !lambda 'return target;'

cover:
  - platform: template
    name: "My Blind"
    id: my_blind
    device_class: blind
    lambda: return id(pot_position).state;
    open_action:
      - stepper.set_target:
          id: my_stepper
          target: 6000
    close_action:
      - stepper.set_target:
          id: my_stepper
          target: 0
    stop_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda return id(my_stepper).current_position;
    position_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda pos * 6000;


stepper:
  - platform: a4988
    id: my_stepper
    step_pin: D1
    dir_pin: D2
    max_speed: 700

    # Optional:
    acceleration: inf
    deceleration: inf
