esphome:
  name: esp01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Wifi"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "backup"
    password: "backuppassword"

captive_portal:

# Enable logging
logger:

ota:

sensor:
  - platform: adc
    pin: A0
    id: pot_position
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0.2 -> 0.0
          - 0.8 -> 1.0
      - lambda: return clamp(x, 0, 1);
  - platform: template
    name: "My Blind Position"
    id: position
    
api:
  services:
    - service: control_blind
      variables:
        target: int
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return target;'
        - sensor.template.publish:
            id: position
            state: !lambda 'return target;'

cover:
  - platform: template
    name: "My Blind"
    id: my_blind
    device_class: blind
    open_action:
      - stepper.set_target:
          id: my_stepper
          target: 6000
      - sensor.template.publish:
          id: position
          state: !lambda return id(my_stepper).target_position;
    close_action:
      - stepper.set_target:
          id: my_stepper
          target: 0
      - sensor.template.publish:
            id: position
            state: !lambda return id(my_stepper).target_position;
    stop_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda return id(my_stepper).current_position;
      - sensor.template.publish:
            id: position
            state: !lambda return id(my_stepper).current_position;
    optimistic: true
    assumed_state: true


stepper:
  - platform: a4988
    id: my_stepper
    step_pin: D1
    dir_pin: D2
    max_speed: 700

    # Optional:
    acceleration: inf
    deceleration: inf