esphome:
  name: esp01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ssid"
    password: "password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    id: pot_position
    update_interval: 0.005s
    filters:
      - calibrate_linear:
          - 0.2 -> 0.0
          - 0.8 -> 1.0
      - lambda: return clamp(x, 0, 1);
    
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50 Hz
    
    
servo:
  - id: my_servo
    output: pwm_output
    transition_length: 2s
    
cover:
  - platform: template
    name: "Template Cover"
    lambda: return id(pot_position);
    has_position: true
    open_action:
      - servo.write:
          id: my_servo
          level: -100.0%
    close_action:
      - servo.write:
          id: my_servo
          level: 37.0%
    stop_action:
      - servo.detach: my_servo
    position_action:
      - servo.write:
          id: my_servo
          level: !lambda return -1.37 * pos + 0.37;
